### PR TITLE
fix: Extend blueprint to include RequestBody properties

### LINKED ISSUE #25: Add missing parameters to request
The blueprint currently doesn't return the request's properties as it should according to openapi spec

openapi schema
Screenshot 2024-07-22 at 20 17 46

blueprint
Screenshot 2024-07-22 at 20 18 14

### PR DESCRIPTION
**Pull request by kainpets**
- The seam-blueprint.test.ts.md snapshot now includes request parameters with appropriate values. 
- @seamapi/types were bumped to latest version which is the cause of other changes to snapshot

 
Closes #25

### CODE REVIEW

File: src/lib/blueprint.ts [hunk 1]
```diff
@@ -304,8 +312,42 @@ const createRequest = (
...
+  if (schema.type !== 'object' || schema.properties == null) {
+    return []
+  }
+
+  const requiredProperties = schema.required ?? []
+
+  return Object.entries(schema.properties).map(
+    ([name, property]: [string, any]): RequestBodyProperty => ({
+      name,
+      type: property.type ?? 'string',
```
Comment (andrii-balitskyi) [inline src/lib/blueprint.ts:345]: why do we default type to `string`?

File: test/snapshots/seam-blueprint.test.ts.md [hunk 2]
```diff
@@ -184,6 +184,14 @@ Generated by [AVA](https://avajs.dev).
               name: 'system_type_display_name',
               type: 'string',
             },
+            {
+              deprecationMessage: '',
+              description: '',
+              isDeprecated: false,
+              isUndocumented: false,
+              name: 'visionline_metadata',
+              type: 'record',
```
Comment (andrii-balitskyi) [inline test/snapshots/seam-blueprint.test.ts.md:193]: Where does `record` type comes from? I haven't seen such a type in our openapi spec, only `object`

File: test/snapshots/seam-blueprint.test.ts.md [hunk 3]
```diff
@@ -219,7 +231,15 @@ Generated by [AVA](https://avajs.dev).
                 methods: [
                   'POST',
                 ],
-                parameters: [],
+                parameters: [
+                  {
+                    description: 'ID of the connected account by which to filter the list of returned access control systems.',
+                    format: 'uuid',
+                    isRequired: [],
```
Comment (andrii-balitskyi) [inline test/snapshots/seam-blueprint.test.ts.md:238]: `[]` value for `isRequired` doesn't seem right

File: src/lib/blueprint.ts [hunk 4]
```diff
@@ -304,8 +312,42 @@ const createRequest = (
...
+      format: property.format,
+      description: property.description ?? '',
+      isRequired: requiredProperties,
```
Comment (andrii-balitskyi) [inline src/lib/blueprint.ts:348]:
```suggestion
      isRequired: requiredProperties.includes(name),
```

File: src/lib/blueprint.ts (hunk 1 above)
Comment (kainpets) [reply src/lib/blueprint.ts:345]: Thought it's better than undefined but probably an empty string is better since it will let us know that something went wrong?

File: test/snapshots/seam-blueprint.test.ts.md (hunk 2 above)
Comment (kainpets) [reply test/snapshots/seam-blueprint.test.ts.md:193]: We have RecordProperty and ObjectProperty interfaces. I think a property without more properties nested will be of type record? Don't remember the reasoning behind this but it's unlikely I came up with this distinction myself. Do we want to only maintain ObjectProperty?

File: src/lib/blueprint.ts (hunk 4 above)
Comment (kainpets) [reply src/lib/blueprint.ts]: I think I got confused and thought isRequired could be an array of required parameters 😓

File: test/snapshots/seam-blueprint.test.ts.md (hunk 2 above)
Comment (andrii-balitskyi) [reply test/snapshots/seam-blueprint.test.ts.md:193]: Oh got it, looks good! I was a bit confused because I thought `record` comes from the openapi spec.

Comment (razor-x) [reply test/snapshots/seam-blueprint.test.ts.md:193]: Custom metadata is an example of a record type.

File: src/lib/blueprint.ts [hunk 5]
```diff
@@ -304,8 +304,51 @@ const createRequest = (
...
+    ([name, property]: [string, any]): Parameter & {
+      type: string
+      format: string
+    } => {
+      const parsedProperty = PropertySchema.parse(property)
+
+      return {
+        name,
+        type: parsedProperty.type,
+        format: property.format,
```
Comment (razor-x) [inline src/lib/blueprint.ts:343]: We need to define these in the blueprint spec. I'm not sure if we need type and format. I guess the main use case for type would be "json type" and format is "semantic meaning". But if we know something is a date or a uuid, then we also know it is a string.

I think at the blueprint level, it's more important to build on the semantics. So we IMO we want

```
export type Property =
  | StringProperty
  | EnumProperty
  | RecordProperty
  | ListProperty
  | ObjectProperty
  | BooleanProperty
  | DatetimeProperty
  | IdProperty
```

but we can still include the low level type info. How about we remove `type` and do

```
interface StringProperty extends BaseProperty {
  format: 'string'
  jsonType: 'string'
}

interface DatetimeProperty extends BaseProperty {
  format: 'datetime'
  jsonType: 'string'
}

// ...
```

**Review by razor-x — APPROVED** [review]
