### PR TITLE
fix: break out Parameter into separate types

### LINKED ISSUE #63: Break up `Parameter` interface into the different types/formats
Really we need to follow what we did for Property and break it up into the difference types/formats.

But that can be the next PR

_Originally posted by @razor-x in https://github.com/seamapi/blueprint/pull/62#discussion_r1727266637_

### PR DESCRIPTION
**Pull request by mikewuu**
closes #63

### CODE REVIEW

File: src/lib/blueprint.ts [hunk 1]
```diff
@@ -50,17 +50,67 @@ export interface Endpoint {
...
+}
+
+interface RecordParameter extends BaseParameter {
+  format: 'record'
+  jsonType: 'object'
+}
+
+interface ListParameter extends BaseParameter {
+  format: 'list'
+  jsonType: 'array'
```
Comment (mikewuu) [inline src/lib/blueprint.ts:80]: Copied this over from `ListProperty` but is `array` correct here? Because `typeof [] === 'object'`

**Review by razor-x — APPROVED** [review]
